on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - 'version.properties'

name: do-alpha-release

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

  build:
    uses: ./.github/workflows/build-apk.yml
    secrets: inherit
    with:
      ref: ${{ github.token }}
      bump_version: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout yet again
        uses: actions/checkout@v2

      - name: Download built APK
        uses: actions/download-artifact@v3
        with:
          name: Signed APK

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.fieldbook.tracker
          releaseFiles: app-release-unsigned-signed.apk
          track: alpha
    