on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'app/build.gradle'

name: do-alpha-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Get Android version
        id: test
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle
    
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle
        versionCode: ${{ steps.test.outputs.versionCode }}+1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew app:assembleRelease 

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: app/build/outputs/

    - name: Release APK to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.fieldbook.tracker
        releaseFiles: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        track: alpha
    
