on:
  push:
     branches:
       - develop

name: do-alpha-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Increment versionCode
      uses: yoichiro/gh-action-increment-value@main
      with:
        target_directory: 'app'
        target_file: 'build.gradle'
        prefix: 'defaultConfig.versionCode":'
        suffix: '}'
        commit_message: 'Increment the versionCode to '

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew app:assembleRelease 

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: app/build/outputs/

    - name: Release APK to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.fieldbook.tracker
        releaseFiles: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        track: alpha
    
