on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - 'version.properties'

name: do-alpha-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build APK
      id: build
      uses: ./build-apk.yml
      with:
        ref: ${{ github.sha }}
        bump_version: true

    - name: Release APK to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.fieldbook.tracker
        releaseFiles: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        track: alpha
    