on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'version.properties'

name: do-github-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Get Android version
      run: |
        MAJOR=$(cat version.properties | grep majorVersion | cut -d = -f 2)
        MINOR=$(cat version.properties | grep minorVersion | cut -d = -f 2)
        PATCH=$(cat version.properties | grep patchVersion | cut -d = -f 2)
        BUILD=$(cat version.properties | grep buildNumber | cut -d = -f 2)
        echo "The version is $MAJOR.$MINOR.$PATCH.$BUILD"
        echo "VERSION=$MAJOR.$MINOR.$PATCH.$BUILD" >> $GITHUB_ENV

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew app:assembleRelease 

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload built APK
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: app/build/outputs/

    - name: Release APK
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: v${{ env.VERSION }}
        tag: ${{ env.VERSION }}
        file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        asset_name: Field-Book-v${{ env.VERSION }}.apk
        overwrite: true
    
