on:
  workflow_dispatch:
  push:
    branches:
      - master

name: do-github-release

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

  build:
    uses: ./.github/workflows/build-apk.yml
    secrets: inherit
    with:
      ref: ${{ github.sha }}
      bump_version: false

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout yet again
        uses: actions/checkout@v2

      - name: Download built APK
        uses: actions/download-artifact@v3
        with:
          name: Signed APK
      
      - name: Get Android version
        run: |
          MAJOR=$(cat version.properties | grep majorVersion | cut -d = -f 2)
          MINOR=$(cat version.properties | grep minorVersion | cut -d = -f 2)
          PATCH=$(cat version.properties | grep patchVersion | cut -d = -f 2)
          BUILD=${{ needs.build.outputs.build_number }}
          echo "The version is $MAJOR.$MINOR.$PATCH.$BUILD"
          echo "VERSION=$MAJOR.$MINOR.$PATCH.$BUILD" >> $GITHUB_ENV
          echo "RELEASE=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Release APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: v${{ env.RELEASE }}
          tag: ${{ env.VERSION }}
          file: app-release-unsigned-signed.apk
          asset_name: Field-Book-v${{ env.RELEASE }}.apk
          overwrite: true
    
