on:
  push:
    branches:
      - master

name: do-github-release

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.save_version.outputs.RELEASE }}
      version_number: ${{ steps.save_version.outputs.VERSION }}
    steps:

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Increment and save build number
        run: |
          sed -i 's/\(buildNumber=\)\([0-9]*\)/echo "\1$((\2+1))"/e' version.properties
          BUILD=$(cat version.properties | grep buildNumber | cut -d = -f 2)
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      # Looks for commit intents following the conventional commits standard, bumps the patch version at minimum
      # Details here https://github.com/oflynned/android-version-bump#workflow and here https://www.conventionalcommits.org/en/v1.0.0/
      - name: Bump version if not a merge from develop
        if: |
          github.ref == 'refs/heads/master' &&
          !contains(github.event.head_commit.message, 'Merge pull request') ||
          !contains(github.event.head_commit.message, 'from PhenoApps/develop')
        uses: oflynned/android-version-bump@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_number: ${{ env.BUILD }}

      - name: Commit just build bump if merge from develop
        if: |
          github.ref == 'refs/heads/master' &&
          contains(github.event.head_commit.message, 'Merge pull request') ||
          contains(github.event.head_commit.message, 'from PhenoApps/develop')
        run: |
          BUILD=$(cat version.properties | grep buildNumber | cut -d = -f 2)
          git config --global user.name "Automated Build Bump"
          git add version.properties
          git commit -m "Automated master build bump to $BUILD [skip-ci]"
          git push
      
      - name: Save version
        id: save_version
        run: |
          MAJOR=$(cat version.properties | grep majorVersion | cut -d = -f 2)
          MINOR=$(cat version.properties | grep minorVersion | cut -d = -f 2)
          PATCH=$(cat version.properties | grep patchVersion | cut -d = -f 2)
          BUILD=$(cat version.properties | grep buildNumber | cut -d = -f 2)
          echo "The version is $MAJOR.$MINOR.$PATCH.$BUILD"
          echo "VERSION=$MAJOR.$MINOR.$PATCH.$BUILD" >> $GITHUB_OUTPUT
          echo "RELEASE=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT

  build-and-release:
    needs: determine-version
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew app:assembleRelease 

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload built APK
        uses: actions/upload-artifact@v2
        with:
          name: Signed APK
          path: app/build/outputs/

      - name: Release APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: v${{ needs.determine-version.outputs.release_name }}
          tag: ${{ needs.determine-version.outputs.version_number }}
          file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          asset_name: Field-Book-v${{ needs.determine-version.outputs.release_name }}.apk
          overwrite: true
    
