on:
  push:
    branches:
      - main

name: do-github-release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Looks for commit intents following the conventional commits standard, bumps the patch version at minimum
      # Details here https://github.com/oflynned/android-version-bump#workflow and here https://www.conventionalcommits.org/en/v1.0.0/
      - name: Bump version
        id: bump_version
        uses: oflynned/android-version-bump@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_number: ${{ github.run_number }} 

      - name: Retrieve version changes
        run: |
          echo "MAJOR_CHANGE=$(git diff HEAD HEAD~1 -- app/version.properties | grep majorVersion || true)" >> $GITHUB_ENV
          echo "MINOR_CHANGE=$(git diff HEAD HEAD~1 -- app/version.properties | grep minorVersion || true)" >> $GITHUB_ENV
          echo "Statuses are major change:$MAJOR_CHANGE and minor change: $MINOR_CHANGE"
          MAJOR=$(cat version.properties | grep majorVersion | cut -d = -f 2)
          MINOR=$(cat version.properties | grep minorVersion | cut -d = -f 2)
          PATCH=$(cat version.properties | grep patchVersion | cut -d = -f 2)
          BUILD=$(cat version.properties | grep buildNumber | cut -d = -f 2)
          echo "VERSION=$MAJOR.$MINOR.$PATCH.$BUILD" >> $GITHUB_ENV
          echo "RELEASE=$MAJOR.$MINOR" >> $GITHUB_ENV
          echo "The version is $VERSION and release is $RELEASE"

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew app:assembleRelease 

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload built APK
        uses: actions/upload-artifact@v2
        with:
          name: Signed APK
          path: app/build/outputs/

      # Updates latest release if just a new patch
      - name: Upload APK
        if: ${{ !env.MAJOR_CHANGE && !env.MINOR_CHANGE }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: v${{ env.RELEASE }}
          tag: ${{ env.VERSION }}
          file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          asset_name: Field-Book-v${{ env.RELEASE }}.apk
          overwrite: true

      # Drafts a new prerelease if major or minor version has changed 
      - name: Upload APK
        if: ${{ env.MAJOR_CHANGE || env.MINOR_CHANGE }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: v${{ env.RELEASE }}
          tag: ${{ env.VERSION }}
          file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          asset_name: Field-Book-v${{ env.RELEASE }}.apk
          prerelease: true
    
