on:
  workflow_dispatch:
  push:
    branches:
      - master

name: do-github-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: Build APK
      id: build
      uses: ./build-apk.yml
      with:
        ref: ${{ github.sha }}
        bump_version: false

    - name: Get Android version
      run: |
        MAJOR=$(cat version.properties | grep majorVersion | cut -d = -f 2)
        MINOR=$(cat version.properties | grep minorVersion | cut -d = -f 2)
        PATCH=$(cat version.properties | grep patchVersion | cut -d = -f 2)
        BUILD=${{ steps.build.outputs.build_number }}
        echo "The version is $MAJOR.$MINOR.$PATCH.$BUILD"
        echo "VERSION=$MAJOR.$MINOR.$PATCH.$BUILD" >> $GITHUB_ENV
        echo "RELEASE=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

    - name: Release APK
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: v${{ env.RELEASE }}
        tag: ${{ env.VERSION }}
        file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        asset_name: Field-Book-v${{ env.RELEASE }}.apk
        overwrite: true
    
