on:
  workflow_dispatch:
    inputs:
      pullRequestName:
        description: 'Pull Request Name'
        required: true
        type: string
      environment:
        description: 'Environment to build from'
        type: environment
        required: true
  pull_request:
    branches:
      - develop

name: build-for-pr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set pull request ref
      run: |
          if [[ ${{ github.event_name == 'workflow_dispatch' }} == true ]]; then
            pr_ref=${{ inputs.pullRequestName }}
          else
            pr_ref=${{ github.event.pull_request.head.sha }}
          fi
          echo "pr_ref=$pr_ref" >> $GITHUB_ENV

    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.pr_ref }}

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Looks for commit intents following the conventional commits standard, bumps the patch version at minimum
    # Details here https://github.com/oflynned/android-version-bump#workflow and here https://www.conventionalcommits.org/en/v1.0.0/
    - name: Bump version
      id: bump_version
      uses: oflynned/android-version-bump@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_number: ${{ github.run_number }}
        tag_prefix: 'v'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew app:assembleRelease 

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload built APK
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: app/build/outputs/
    
    - name: Rename APK file
      run: mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/Field-Book-v${{ steps.bump_version.outputs.new_tag }}-prerelease.apk

    - name: Attach APK to PR
      uses: gavv/pull-request-artifacts@v1.0.0
      with:
        commit: ${{ github.event.pull_request.head.sha }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: |
          app/build/outputs/apk/release/Field-Book-v${{ steps.bump_version.outputs.new_tag }}-prerelease.apk

    
