on:
  pull_request:
    branches:
      - main

name: do-pr-prerelease

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout PR Head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew app:assembleRelease 

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload built APK${{ env.VERSION }}
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
      
      - name: Rename APK file
        run: mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/Field-Book-prerelease.apk

      - name: Attach APK to PR using artifacts branch
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts: |
            app/build/outputs/apk/release/Field-Book-prerelease.apk
