on:
  push:
    branches:
      - main

name: update-changelog

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.ACTIONS_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          fetch-depth: 0
      
      - name: Extract changelog entry from PR
        id: extract_changelog
        run: |
          # Get the latest commit SHA
          commit_sha=$(git log -1 --format="%H")
          echo "Commit SHA: $commit_sha"

          # Find the pull request associated with the commit
          pr_number=$(gh api -X GET "repos/${{ github.repository }}/commits/$commit_sha/pulls" --jq '.[0].number')

          # Exit gracefully if no PR is found
          if [ -z "$pr_number" ]; then
            echo "No associated PR found for commit $commit_sha."
            exit 0
          fi

          # Get the PR body and extract release note
          pr_body=$(gh api -X GET "repos/${{ github.repository }}/pulls/$pr_number" --jq '.body' | sed 's/\r//g')
          changelog_entry=$(echo "$pr_body" | awk 'BEGIN { found=0 } /```release-note/ { found=1; next } /```/ { found=0 } found { print }' | sed '/^$/d')

          # Exit if no changelog entry found
          if [ -z "$changelog_entry" ]; then
            echo "No changelog entry found."
            exit 0
          fi

          # Detect change type
          change_type=$(echo "$pr_body" | grep -oP '(?<=- \[x\] `)[A-Z]+(?=`)' | head -n 1)
          case "$change_type" in
            "ADDITION")
              section="### Added"
              ;;
            "CHANGE")
              section="### Changed"
              ;;
            "FIX")
              section="### Fixed"
              ;;
            "OTHER")
              section="### Miscellaneous"
              ;;
            *)
              echo "Unknown change type: $change_type"
              exit 1
              ;;
          esac

          # Store the extracted information in environment variables
          pr_url="https://github.com/${{ github.repository }}/pull/$pr_number"
          echo "changelog=${changelog_entry} ($pr_url)" >> $GITHUB_ENV
          echo "section=$section" >> $GITHUB_ENV
          echo "pr_number=$pr_number" >> $GITHUB_ENV

      - name: Extract version bump type from PR body
        id: extract_version_bump
        run: |
          pr_body=$(gh api -X GET "repos/${{ github.repository }}/pulls/${{ env.pr_number }}" --jq '.body' | sed 's/\r//g')
          major_checked=$(echo "$pr_body" | grep -q '\[x\] `MAJOR`' && echo "true" || echo "false")
          minor_checked=$(echo "$pr_body" | grep -q '\[x\] `MINOR`' && echo "true" || echo "false")
          patch_checked=$(echo "$pr_body" | grep -q '\[x\] `PATCH`' && echo "true" || echo "false")

          if [ "$major_checked" == "true" ]; then
            echo "BUMP_TYPE=major" >> $GITHUB_ENV
          elif [ "$minor_checked" == "true" ]; then
            echo "BUMP_TYPE=minor" >> $GITHUB_ENV
          elif [ "$patch_checked" == "true" ]; then
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
          else
            echo "No release bump required."
            exit 0
          fi
          
      - name: Dispatch GitHub Release Action
        if: env.BUMP_TYPE != '' # Ensures no action if NO RELEASE is selected
        run: |
          echo "Triggering release action with bump type: ${{ env.BUMP_TYPE }}"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "trigger-release", "client_payload": {"bump_type": "${{ env.BUMP_TYPE }}"}}'

      - name: Add entry to changelog
        if: env.pr_number != ''
        run: |
          # Insert the changelog entry under the first matching section in Unreleased (avoids / delimeter to not conflict with url)
          sed -i "0,/${{ env.section }}/s@${{ env.section }}@${{ env.section }}\n- ${{ env.changelog }}@" CHANGELOG.md

          # Show the updated changelog
          cat CHANGELOG.md

      - name: Commit and push changelog update
        if: env.pr_number != ''
        uses: EndBug/add-and-commit@v7
        with:
          add: 'CHANGELOG.md'
          message: "Update CHANGELOG.md with entry from PR #${{ env.pr_number }}"
          author_email: git-action-bot@example.com
          author_name: Git Action Bot
          token: ${{ secrets.GITHUB_TOKEN }}
          push: true
