name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.ACTIONS_PAT }}  # Use GitHub Personal Access Token for `gh` CLI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          fetch-depth: 0  # Ensure the entire repo is fetched, including all branches

      - name: Extract changelog entry from merged PR
        id: extract_changelog
        run: |
          # Get the latest commit SHA that triggered the push event
          commit_sha=$(git log -1 --format="%H")
          echo "Commit SHA: $commit_sha"
          
          # Use the GitHub API to find the pull request associated with the commit SHA
          pr_number=$(gh api -X GET "repos/${{ github.repository }}/commits/$commit_sha/pulls" --jq '.[0].number')

          # Exit if no PR is found
          if [ -z "$pr_number" ]; then
            echo "No associated PR found for commit $commit_sha."
            exit 1
          fi
          echo "PR Number: $pr_number"

          # Retrieve the PR body using the GitHub API
          pr_body=$(gh api -X GET "repos/${{ github.repository }}/pulls/$pr_number" --jq '.body')

          # Print the PR body for debugging
          echo "Full PR Body Content:"
          echo "$pr_body"

          # Use grep and sed to extract the release note content between ```release-note and ```
          changelog_entry=$(echo "$pr_body" | grep -oP '(?<=```release-note)[\s\S]*(?=```)' | sed 's/\r//g' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          
          # Debugging: Print the changelog entry
          echo "Changelog Entry: $changelog_entry"

          # Exit if the changelog entry is empty
          if [ -z "$changelog_entry" ]; then
            echo "No changelog entry found in the PR body."
            exit 1
          fi

          # Store the changelog entry as an environment variable
          echo "changelog=$changelog_entry" >> $GITHUB_ENV

      - name: Append changelog entry to CHANGELOG.md
        run: |
          # Check if CHANGELOG.md exists, create it if not
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
          fi

          # Append the changelog entry with a date header to CHANGELOG.md
          echo -e "\n## $(date +'%Y-%m-%d')\n${{ env.changelog }}" >> CHANGELOG.md
          cat CHANGELOG.md

      - name: Commit and push updated changelog
        uses: EndBug/add-and-commit@v7
        with:
          add: 'CHANGELOG.md'
          message: "Update CHANGELOG.md with entry from PR #${{ steps.extract_changelog.outputs.pr_number }}"
          author_email: git-action-bot@example.com
          author_name: Git Action Bot
          token: ${{ secrets.GITHUB_TOKEN }}
          push: true