name: Version testing
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get Android version
        id: test
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts 
      - name: Get the output
        run: |
          echo "The versionCode was ${{ steps.test.outputs.versionCode }}"
          echo "The versionName was ${{ steps.test.outputs.versionName }}"
